-- Re-import COUNTRY from NOMIS as updates where made my Connect DPS team

DELETE
FROM reference_codes
WHERE group_code = 'COUNTRY';

INSERT INTO reference_codes (group_code, code, description, display_order, is_active, created_by)
VALUES ('COUNTRY', 'ENG', 'England', 1, true, 'JAMES'),
       ('COUNTRY', 'WALES', 'Wales', 2, true, 'JAMES'),
       ('COUNTRY', 'SCOT', 'Scotland', 3, true, 'JAMES'),
       ('COUNTRY', 'NI', 'Northern Ireland', 4, true, 'JAMES'),
       ('COUNTRY', 'ABW', 'Aruba', 99, true, 'JAMES'),
       ('COUNTRY', 'AFG', 'Afghanistan', 99, true, 'JAMES'),
       ('COUNTRY', 'AGO', 'Angola', 99, true, 'JAMES'),
       ('COUNTRY', 'AIA', 'Anguilla', 99, true, 'JAMES'),
       ('COUNTRY', 'AKR', 'Akrotiri', 99, true, 'JAMES'),
       ('COUNTRY', 'ALA', 'Aland Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'ALB', 'Albania', 99, true, 'JAMES'),
       ('COUNTRY', 'AND', 'Andorra', 99, true, 'JAMES'),
       ('COUNTRY', 'ANT', 'Netherlands Antilles', 99, true, 'JAMES'),
       ('COUNTRY', 'ARE', 'The United Arab Emirates', 99, true, 'JAMES'),
       ('COUNTRY', 'ARG', 'Argentina', 99, true, 'JAMES'),
       ('COUNTRY', 'ARM', 'Armenia', 99, true, 'JAMES'),
       ('COUNTRY', 'ASM', 'American Samoa', 99, true, 'JAMES'),
       ('COUNTRY', 'ATA', 'British Antarctic Territory', 99, true, 'JAMES'),
       ('COUNTRY', 'ATF', 'French Southern Territories', 99, true, 'JAMES'),
       ('COUNTRY', 'ATG', 'Antigua And Barbuda', 99, true, 'JAMES'),
       ('COUNTRY', 'AUS', 'Australia', 99, true, 'JAMES'),
       ('COUNTRY', 'AUT', 'Austria', 99, true, 'JAMES'),
       ('COUNTRY', 'AZE', 'Azerbaijan', 99, true, 'JAMES'),
       ('COUNTRY', 'BDI', 'Burundi', 99, true, 'JAMES'),
       ('COUNTRY', 'BEL', 'Belgium', 99, true, 'JAMES'),
       ('COUNTRY', 'BEN', 'Benin', 99, true, 'JAMES'),
       ('COUNTRY', 'BES', 'Bonaire, Sint Eustatius and Saba', 99, true, 'JAMES'),
       ('COUNTRY', 'BFA', 'Burkina Faso', 99, true, 'JAMES'),
       ('COUNTRY', 'BGD', 'Bangladesh', 99, true, 'JAMES'),
       ('COUNTRY', 'BGR', 'Bulgaria', 99, true, 'JAMES'),
       ('COUNTRY', 'BHR', 'Bahrain', 99, true, 'JAMES'),
       ('COUNTRY', 'BHS', 'Tha Bahamas', 99, true, 'JAMES'),
       ('COUNTRY', 'BIH', 'Bosnia And Herzegovina', 99, true, 'JAMES'),
       ('COUNTRY', 'BLM', 'Saint-Barthelemy', 99, true, 'JAMES'),
       ('COUNTRY', 'BLR', 'Belarus', 99, true, 'JAMES'),
       ('COUNTRY', 'BLZ', 'Belize', 99, true, 'JAMES'),
       ('COUNTRY', 'BMU', 'Bermuda', 99, true, 'JAMES'),
       ('COUNTRY', 'BOL', 'Bolivia', 99, true, 'JAMES'),
       ('COUNTRY', 'BRA', 'Brazil', 99, true, 'JAMES'),
       ('COUNTRY', 'BRB', 'Barbados', 99, true, 'JAMES'),
       ('COUNTRY', 'BRN', 'Brunei', 99, true, 'JAMES'),
       ('COUNTRY', 'BTN', 'Bhutan', 99, true, 'JAMES'),
       ('COUNTRY', 'BVT', 'Bouvet Island', 99, true, 'JAMES'),
       ('COUNTRY', 'BWA', 'Botswana', 99, true, 'JAMES'),
       ('COUNTRY', 'CAF', 'Central African Republic', 99, true, 'JAMES'),
       ('COUNTRY', 'CAN', 'Canada', 99, true, 'JAMES'),
       ('COUNTRY', 'CCK', 'Cocos (Keeling) Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'CHE', 'Switzerland', 99, true, 'JAMES'),
       ('COUNTRY', 'CHL', 'Chile', 99, true, 'JAMES'),
       ('COUNTRY', 'CHN', 'China', 99, true, 'JAMES'),
       ('COUNTRY', 'CI', 'Channel Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'CIV', 'Ivory Coast', 99, true, 'JAMES'),
       ('COUNTRY', 'CMR', 'Cameroon', 99, true, 'JAMES'),
       ('COUNTRY', 'COD', 'Congo (Democratic Republic)', 99, true, 'JAMES'),
       ('COUNTRY', 'COG', 'Congo', 99, true, 'JAMES'),
       ('COUNTRY', 'COK', 'Cook Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'COL', 'Colombia', 99, true, 'JAMES'),
       ('COUNTRY', 'COM', 'Comoros', 99, true, 'JAMES'),
       ('COUNTRY', 'CPV', 'Cape Verde', 99, true, 'JAMES'),
       ('COUNTRY', 'CRI', 'Costa Rica', 99, true, 'JAMES'),
       ('COUNTRY', 'CUB', 'Cuba', 99, true, 'JAMES'),
       ('COUNTRY', 'CUW', 'Curacao', 99, true, 'JAMES'),
       ('COUNTRY', 'CXR', 'Christmas Island', 99, true, 'JAMES'),
       ('COUNTRY', 'CYM', 'Cayman Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'CYP', 'Cyprus', 99, true, 'JAMES'),
       ('COUNTRY', 'CZE', 'The Czech Republic', 99, true, 'JAMES'),
       ('COUNTRY', 'DEU', 'Germany', 99, true, 'JAMES'),
       ('COUNTRY', 'DJI', 'Djibouti', 99, true, 'JAMES'),
       ('COUNTRY', 'DKL', 'Dhekelia', 99, true, 'JAMES'),
       ('COUNTRY', 'DMA', 'Dominica', 99, true, 'JAMES'),
       ('COUNTRY', 'DNK', 'Denmark', 99, true, 'JAMES'),
       ('COUNTRY', 'DOM', 'Dominican Republic', 99, true, 'JAMES'),
       ('COUNTRY', 'DZA', 'Algeria', 99, true, 'JAMES'),
       ('COUNTRY', 'ECU', 'Ecuador', 99, true, 'JAMES'),
       ('COUNTRY', 'EGY', 'Egypt', 99, true, 'JAMES'),
       ('COUNTRY', 'ERI', 'Eritrea', 99, true, 'JAMES'),
       ('COUNTRY', 'ESH', 'Western Sahara', 99, true, 'JAMES'),
       ('COUNTRY', 'ESP', 'Spain', 99, true, 'JAMES'),
       ('COUNTRY', 'EST', 'Estonia', 99, true, 'JAMES'),
       ('COUNTRY', 'ETH', 'Ethiopia', 99, true, 'JAMES'),
       ('COUNTRY', 'FIN', 'Finland', 99, true, 'JAMES'),
       ('COUNTRY', 'FJI', 'Fiji', 99, true, 'JAMES'),
       ('COUNTRY', 'FLK', 'Falkland Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'FRA', 'France', 99, true, 'JAMES'),
       ('COUNTRY', 'FRO', 'Faroe Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'FSM', 'Federated States Of Micronesia', 99, true, 'JAMES'),
       ('COUNTRY', 'GAB', 'Gabon', 99, true, 'JAMES'),
       ('COUNTRY', 'GBR', 'United Kingdom', 99, true, 'JAMES'),
       ('COUNTRY', 'GEO', 'Georgia', 99, true, 'JAMES'),
       ('COUNTRY', 'GGY', 'Guernsey, Alderney, Sark', 99, true, 'JAMES'),
       ('COUNTRY', 'GHA', 'Ghana', 99, true, 'JAMES'),
       ('COUNTRY', 'GIB', 'Gibraltar', 99, true, 'JAMES'),
       ('COUNTRY', 'GIN', 'Guinea', 99, true, 'JAMES'),
       ('COUNTRY', 'GLP', 'Guadeloupe', 99, true, 'JAMES'),
       ('COUNTRY', 'GMB', 'The Gambia', 99, true, 'JAMES'),
       ('COUNTRY', 'GNB', 'Guinea-Bissau', 99, true, 'JAMES'),
       ('COUNTRY', 'GNQ', 'Equatorial Guinea', 99, true, 'JAMES'),
       ('COUNTRY', 'GRC', 'Greece', 99, true, 'JAMES'),
       ('COUNTRY', 'GRD', 'Grenada', 99, true, 'JAMES'),
       ('COUNTRY', 'GRL', 'Greenland', 99, true, 'JAMES'),
       ('COUNTRY', 'GTM', 'Guatemala', 99, true, 'JAMES'),
       ('COUNTRY', 'GUF', 'French Guiana', 99, true, 'JAMES'),
       ('COUNTRY', 'GUM', 'Guam', 99, true, 'JAMES'),
       ('COUNTRY', 'GUY', 'Guyana', 99, true, 'JAMES'),
       ('COUNTRY', 'HKG', 'Hong Kong', 99, true, 'JAMES'),
       ('COUNTRY', 'HMD', 'Heard And Mcdonald Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'HND', 'Honduras', 99, true, 'JAMES'),
       ('COUNTRY', 'HRV', 'Croatia', 99, true, 'JAMES'),
       ('COUNTRY', 'HTI', 'Haiti', 99, true, 'JAMES'),
       ('COUNTRY', 'HUN', 'Hungary', 99, true, 'JAMES'),
       ('COUNTRY', 'IDN', 'Indonesia', 99, true, 'JAMES'),
       ('COUNTRY', 'IND', 'India', 99, true, 'JAMES'),
       ('COUNTRY', 'IOM', 'Isle of Man', 99, true, 'JAMES'),
       ('COUNTRY', 'IOT', 'British Indian Ocean Territory', 99, true, 'JAMES'),
       ('COUNTRY', 'IRL', 'Ireland', 99, true, 'JAMES'),
       ('COUNTRY', 'IRN', 'Iran', 99, true, 'JAMES'),
       ('COUNTRY', 'IRQ', 'Iraq', 99, true, 'JAMES'),
       ('COUNTRY', 'ISL', 'Iceland', 99, true, 'JAMES'),
       ('COUNTRY', 'ISR', 'Israel', 99, true, 'JAMES'),
       ('COUNTRY', 'ITA', 'Italy', 99, true, 'JAMES'),
       ('COUNTRY', 'JAM', 'Jamaica', 99, true, 'JAMES'),
       ('COUNTRY', 'JEY', 'Jersey', 99, true, 'JAMES'),
       ('COUNTRY', 'JOR', 'Jordan', 99, true, 'JAMES'),
       ('COUNTRY', 'JPN', 'Japan', 99, true, 'JAMES'),
       ('COUNTRY', 'KAZ', 'Kazakhstan', 99, true, 'JAMES'),
       ('COUNTRY', 'KEN', 'Kenya', 99, true, 'JAMES'),
       ('COUNTRY', 'KGZ', 'Kyrgyzstan', 99, true, 'JAMES'),
       ('COUNTRY', 'KHM', 'Cambodia', 99, true, 'JAMES'),
       ('COUNTRY', 'KIR', 'Kiribati', 99, true, 'JAMES'),
       ('COUNTRY', 'KNA', 'St Kitts And Nevis', 99, true, 'JAMES'),
       ('COUNTRY', 'KOR', 'South Korea', 99, true, 'JAMES'),
       ('COUNTRY', 'KOS', 'Kosovo', 99, true, 'JAMES'),
       ('COUNTRY', 'KWT', 'Kuwait', 99, true, 'JAMES'),
       ('COUNTRY', 'LAO', 'Laos', 99, true, 'JAMES'),
       ('COUNTRY', 'LBN', 'Lebanon', 99, true, 'JAMES'),
       ('COUNTRY', 'LBR', 'Liberia', 99, true, 'JAMES'),
       ('COUNTRY', 'LBY', 'Libya', 99, true, 'JAMES'),
       ('COUNTRY', 'LCA', 'St Lucia', 99, true, 'JAMES'),
       ('COUNTRY', 'LIE', 'Liechtenstein', 99, true, 'JAMES'),
       ('COUNTRY', 'LKA', 'Sri Lanka', 99, true, 'JAMES'),
       ('COUNTRY', 'LSO', 'Lesotho', 99, true, 'JAMES'),
       ('COUNTRY', 'LTU', 'Lithuania', 99, true, 'JAMES'),
       ('COUNTRY', 'LUX', 'Luxembourg', 99, true, 'JAMES'),
       ('COUNTRY', 'LVA', 'Latvia', 99, true, 'JAMES'),
       ('COUNTRY', 'MAC', 'Macau', 99, true, 'JAMES'),
       ('COUNTRY', 'MAF', 'Saint-Martin (France)', 99, true, 'JAMES'),
       ('COUNTRY', 'MAR', 'Morocco', 99, true, 'JAMES'),
       ('COUNTRY', 'MCO', 'Monaco', 99, true, 'JAMES'),
       ('COUNTRY', 'MDA', 'Moldova', 99, true, 'JAMES'),
       ('COUNTRY', 'MDG', 'Madagascar', 99, true, 'JAMES'),
       ('COUNTRY', 'MDV', 'Maldives', 99, true, 'JAMES'),
       ('COUNTRY', 'MEX', 'Mexico', 99, true, 'JAMES'),
       ('COUNTRY', 'MHL', 'Marshall Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'MKD', 'North Macedonia', 99, true, 'JAMES'),
       ('COUNTRY', 'MLI', 'Mali', 99, true, 'JAMES'),
       ('COUNTRY', 'MLT', 'Malta', 99, true, 'JAMES'),
       ('COUNTRY', 'MMR', 'Myanmar (Burma)', 99, true, 'JAMES'),
       ('COUNTRY', 'MNE', 'Montenegro', 99, true, 'JAMES'),
       ('COUNTRY', 'MNG', 'Mongolia', 99, true, 'JAMES'),
       ('COUNTRY', 'MNP', 'Northern Mariana Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'MOZ', 'Mozambique', 99, true, 'JAMES'),
       ('COUNTRY', 'MRT', 'Mauritania', 99, true, 'JAMES'),
       ('COUNTRY', 'MSR', 'Montserrat', 99, true, 'JAMES'),
       ('COUNTRY', 'MTQ', 'Martinique', 99, true, 'JAMES'),
       ('COUNTRY', 'MUS', 'Mauritius', 99, true, 'JAMES'),
       ('COUNTRY', 'MWI', 'Malawi', 99, true, 'JAMES'),
       ('COUNTRY', 'MYS', 'Malaysia', 99, true, 'JAMES'),
       ('COUNTRY', 'MYT', 'Mayotte', 99, true, 'JAMES'),
       ('COUNTRY', 'NAM', 'Namibia', 99, true, 'JAMES'),
       ('COUNTRY', 'NCL', 'New Caledonia', 99, true, 'JAMES'),
       ('COUNTRY', 'NER', 'Niger', 99, true, 'JAMES'),
       ('COUNTRY', 'NFK', 'Norfolk Island', 99, true, 'JAMES'),
       ('COUNTRY', 'NGA', 'Nigeria', 99, true, 'JAMES'),
       ('COUNTRY', 'NIC', 'Nicaragua', 99, true, 'JAMES'),
       ('COUNTRY', 'NIU', 'Niue', 99, true, 'JAMES'),
       ('COUNTRY', 'NLD', 'Netherlands', 99, true, 'JAMES'),
       ('COUNTRY', 'NOR', 'Norway', 99, true, 'JAMES'),
       ('COUNTRY', 'NPL', 'Nepal', 99, true, 'JAMES'),
       ('COUNTRY', 'NRU', 'Nauru', 99, true, 'JAMES'),
       ('COUNTRY', 'NZL', 'New Zealand', 99, true, 'JAMES'),
       ('COUNTRY', 'OMN', 'Oman', 99, true, 'JAMES'),
       ('COUNTRY', 'PAK', 'Pakistan', 99, true, 'JAMES'),
       ('COUNTRY', 'PAN', 'Panama', 99, true, 'JAMES'),
       ('COUNTRY', 'PCN', 'Pitcairn, Henderson, Ducie and Oeno', 99, true, 'JAMES'),
       ('COUNTRY', 'PER', 'Peru', 99, true, 'JAMES'),
       ('COUNTRY', 'PHL', 'Philippines', 99, true, 'JAMES'),
       ('COUNTRY', 'PLW', 'Palau', 99, true, 'JAMES'),
       ('COUNTRY', 'PNG', 'Papua New Guinea', 99, true, 'JAMES'),
       ('COUNTRY', 'POL', 'Poland', 99, true, 'JAMES'),
       ('COUNTRY', 'PRI', 'Puerto Rico', 99, true, 'JAMES'),
       ('COUNTRY', 'PRK', 'North Korea', 99, true, 'JAMES'),
       ('COUNTRY', 'PRT', 'Portugal', 99, true, 'JAMES'),
       ('COUNTRY', 'PRY', 'Paraguay', 99, true, 'JAMES'),
       ('COUNTRY', 'PSE', 'The Occupied Palestinian Territories', 99, true, 'JAMES'),
       ('COUNTRY', 'PYF', 'French Polynesia', 99, true, 'JAMES'),
       ('COUNTRY', 'QAT', 'Qatar', 99, true, 'JAMES'),
       ('COUNTRY', 'REU', 'Réunion', 99, true, 'JAMES'),
       ('COUNTRY', 'ROM', 'Romania', 99, true, 'JAMES'),
       ('COUNTRY', 'RUS', 'Russia', 99, true, 'JAMES'),
       ('COUNTRY', 'RWA', 'Rwanda', 99, true, 'JAMES'),
       ('COUNTRY', 'SAU', 'Saudi Arabia', 99, true, 'JAMES'),
       ('COUNTRY', 'SDN', 'Sudan', 99, true, 'JAMES'),
       ('COUNTRY', 'SEN', 'Senegal', 99, true, 'JAMES'),
       ('COUNTRY', 'SGP', 'Singapore', 99, true, 'JAMES'),
       ('COUNTRY', 'SGS', 'South Georgia And South Sandwich Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'SHN', 'St Helena, Ascension & Tristan da Cunha', 99, true, 'JAMES'),
       ('COUNTRY', 'SJM', 'Svalbard And Jan Mayen', 99, true, 'JAMES'),
       ('COUNTRY', 'SLB', 'Solomon Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'SLE', 'Sierra Leone', 99, true, 'JAMES'),
       ('COUNTRY', 'SLV', 'El Salvador', 99, true, 'JAMES'),
       ('COUNTRY', 'SMR', 'San Marino', 99, true, 'JAMES'),
       ('COUNTRY', 'SOM', 'Somalia', 99, true, 'JAMES'),
       ('COUNTRY', 'SPM', 'Saint Pierre And Miquelon', 99, true, 'JAMES'),
       ('COUNTRY', 'SRB', 'Serbia', 99, true, 'JAMES'),
       ('COUNTRY', 'SSD', 'South Sudan', 99, true, 'JAMES'),
       ('COUNTRY', 'STP', 'Sao Tome And Principe', 99, true, 'JAMES'),
       ('COUNTRY', 'SUR', 'Suriname', 99, true, 'JAMES'),
       ('COUNTRY', 'SVK', 'Slovakia', 99, true, 'JAMES'),
       ('COUNTRY', 'SVN', 'Slovenia', 99, true, 'JAMES'),
       ('COUNTRY', 'SWE', 'Sweden', 99, true, 'JAMES'),
       ('COUNTRY', 'SWZ', 'Eswatini', 99, true, 'JAMES'),
       ('COUNTRY', 'SXM', 'Sint Maarten (Dutch)', 99, true, 'JAMES'),
       ('COUNTRY', 'SYC', 'Seychelles', 99, true, 'JAMES'),
       ('COUNTRY', 'SYR', 'Syria', 99, true, 'JAMES'),
       ('COUNTRY', 'TCA', 'Turks And Caicos Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'TCD', 'Chad', 99, true, 'JAMES'),
       ('COUNTRY', 'TGO', 'Togo', 99, true, 'JAMES'),
       ('COUNTRY', 'THA', 'Thailand', 99, true, 'JAMES'),
       ('COUNTRY', 'TJK', 'Tajikistan', 99, true, 'JAMES'),
       ('COUNTRY', 'TKL', 'Tokelau', 99, true, 'JAMES'),
       ('COUNTRY', 'TKM', 'Turkmenistan', 99, true, 'JAMES'),
       ('COUNTRY', 'TLS', 'East Timor', 99, true, 'JAMES'),
       ('COUNTRY', 'TON', 'Tonga', 99, true, 'JAMES'),
       ('COUNTRY', 'TTO', 'Trinidad And Tobago', 99, true, 'JAMES'),
       ('COUNTRY', 'TUN', 'Tunisia', 99, true, 'JAMES'),
       ('COUNTRY', 'TUR', 'Turkey', 99, true, 'JAMES'),
       ('COUNTRY', 'TUV', 'Tuvalu', 99, true, 'JAMES'),
       ('COUNTRY', 'TWN', 'Taiwan', 99, true, 'JAMES'),
       ('COUNTRY', 'TZA', 'Tanzania', 99, true, 'JAMES'),
       ('COUNTRY', 'UGA', 'Uganda', 99, true, 'JAMES'),
       ('COUNTRY', 'UKR', 'Ukraine', 99, true, 'JAMES'),
       ('COUNTRY', 'UMI', 'United States Minor Outlying Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'URY', 'Uruguay', 99, true, 'JAMES'),
       ('COUNTRY', 'USA', 'United States', 99, true, 'JAMES'),
       ('COUNTRY', 'UZB', 'Uzbekistan', 99, true, 'JAMES'),
       ('COUNTRY', 'VAT', 'Vatican City', 99, true, 'JAMES'),
       ('COUNTRY', 'VCT', 'St Vincent', 99, true, 'JAMES'),
       ('COUNTRY', 'VEN', 'Venezuela', 99, true, 'JAMES'),
       ('COUNTRY', 'VGB', 'British Virgin Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'VIR', 'United States Virgin Islands', 99, true, 'JAMES'),
       ('COUNTRY', 'VNM', 'Vietnam', 99, true, 'JAMES'),
       ('COUNTRY', 'VUT', 'Vanuatu', 99, true, 'JAMES'),
       ('COUNTRY', 'WLF', 'Wallis And Futuna', 99, true, 'JAMES'),
       ('COUNTRY', 'WSM', 'Samoa', 99, true, 'JAMES'),
       ('COUNTRY', 'XRK', 'Sark', 99, true, 'JAMES'),
       ('COUNTRY', 'YEM', 'Yemen', 99, true, 'JAMES'),
       ('COUNTRY', 'ZAF', 'South Africa', 99, true, 'JAMES'),
       ('COUNTRY', 'ZMB', 'Zambia', 99, true, 'JAMES'),
       ('COUNTRY', 'ZWE', 'Zimbabwe', 99, true, 'JAMES'),
       ('COUNTRY', 'FXX', 'France, Metropolitan', 99, false, 'JAMES'),
       ('COUNTRY', 'SCG', 'Serbia And Montenegro', 99, false, 'JAMES'),
       ('COUNTRY', 'SU', 'USSR', 99, false, 'JAMES'),
       ('COUNTRY', 'YU', 'Yugoslavia', 99, false, 'JAMES'),
       ('COUNTRY', 'XY', 'Refused', 99, false, 'JAMES'),
       ('COUNTRY', 'XZ', 'Stateless', 99, false, 'JAMES'),
       ('COUNTRY', 'XX', 'Unknown', 99, false, 'JAMES');
