-- Remove double spaces from county names

update reference_codes set description = 'Isle of Anglesey' where code = 'ANGLESEY' and group_code = 'COUNTY';
update reference_codes set description = 'Argyll and Bute' where code = 'ARGYLL' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Arran' where code = 'ARRAN' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Barra' where code = 'BARRA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Benbecula' where code = 'BENBECULA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Canna' where code = 'CANNA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Colonsay' where code = 'COLONSAY' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Cumbrae' where code = 'CUMBRAE' and group_code = 'COUNTY';
update reference_codes set description = 'Dumfries and Galloway' where code = 'DUMFRIES' and group_code = 'COUNTY';
update reference_codes set description = 'East Riding of Yorkshire' where code = 'E.YORKSHIRE' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Gigha' where code = 'GIGHA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Harris' where code = 'HARRIS' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Wight' where code = 'I.O.W' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Islay' where code = 'ISLAY' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Bute' where code = 'ISLE_OF_BUTE' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Coll' where code = 'ISLE_OF_COLL' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Eigg' where code = 'ISLE_OF_EIGG' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Iona' where code = 'ISLE_OF_IONA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Jura' where code = 'ISLE_OF_JURA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Man' where code = 'ISLE_OF_MAN' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Mull' where code = 'ISLE_OF_MULL' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Rum' where code = 'ISLE_OF_RUM' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Skye' where code = 'ISLE_OF_SKYE' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Orkney' where code = 'ISLE_ORKNEY' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Lewis' where code = 'LEWIS' and group_code = 'COUNTY';
update reference_codes set description = 'North East Lincolnshire' where code = 'NE.LINCS' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of North Uist' where code = 'NORTH_UIST' and group_code = 'COUNTY';
update reference_codes set description = 'Perth and Kinross' where code = 'PERTHSHIRE' and group_code = 'COUNTY';
update reference_codes set description = 'Rhondda Cynon Taff' where code = 'RHONDDA' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Rhum' where code = 'RHUM' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Scalpay' where code = 'SCALPAY' and group_code = 'COUNTY';
update reference_codes set description = 'Isles Of Scilly' where code = 'SCILLY_ISLES' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Shetland' where code = 'SHETLAND' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of South Uist' where code = 'SOUTH_UIST' and group_code = 'COUNTY';
update reference_codes set description = 'Isle Of Tiree' where code = 'TIREE' and group_code = 'COUNTY';
update reference_codes set description = 'Tyne And Wear' where code = 'TYNE&WEAR' and group_code = 'COUNTY';
update reference_codes set description = 'Vale of Glamorgan' where code = 'W.GLAM' and group_code = 'COUNTY';
