-- Re-import LANG from NOMIS as updates where made my Connect DPS team

DELETE
FROM reference_codes
WHERE group_code = 'LANGUAGE';

INSERT INTO reference_codes (group_code, code, description, display_order, is_active, created_by)
VALUES ('LANGUAGE', 'WEL-CYM', 'Welsh', 1, true, 'JAMES'),
       ('LANGUAGE', 'SCO', 'Scots', 1, true, 'JAMES'),
       ('LANGUAGE', 'ENG', 'English', 1, true, 'JAMES'),
       ('LANGUAGE', 'BSL', 'British Sign Language', 1, true, 'JAMES'),
       ('LANGUAGE', 'CZE-CES', 'Czech', 2, true, 'JAMES'),
       ('LANGUAGE', 'DAN', 'Danish', 2, true, 'JAMES'),
       ('LANGUAGE', 'DUT-NLD', 'Dutch or Flemish', 2, true, 'JAMES'),
       ('LANGUAGE', 'EST', 'Estonian', 2, true, 'JAMES'),
       ('LANGUAGE', 'FIN', 'Finnish', 2, true, 'JAMES'),
       ('LANGUAGE', 'FRE-FRA', 'French', 2, true, 'JAMES'),
       ('LANGUAGE', 'GEO-KAT', 'Georgian', 2, true, 'JAMES'),
       ('LANGUAGE', 'GER-DEU', 'German', 2, true, 'JAMES'),
       ('LANGUAGE', 'GRE-ELL', 'Greek', 2, true, 'JAMES'),
       ('LANGUAGE', 'HUN', 'Hungarian', 2, true, 'JAMES'),
       ('LANGUAGE', 'ITA', 'Italian', 2, true, 'JAMES'),
       ('LANGUAGE', 'LAV', 'Latvian', 2, true, 'JAMES'),
       ('LANGUAGE', 'LIT', 'Lithuanian', 2, true, 'JAMES'),
       ('LANGUAGE', 'MAC-MKD', 'Macedonian', 2, true, 'JAMES'),
       ('LANGUAGE', 'NOR', 'Norwegian', 2, true, 'JAMES'),
       ('LANGUAGE', 'POL', 'Polish', 2, true, 'JAMES'),
       ('LANGUAGE', 'POR', 'Portuguese', 2, true, 'JAMES'),
       ('LANGUAGE', 'ROM', 'Romany', 2, true, 'JAMES'),
       ('LANGUAGE', 'RUM-RON', 'Romanian', 2, true, 'JAMES'),
       ('LANGUAGE', 'RUS', 'Russian', 2, true, 'JAMES'),
       ('LANGUAGE', 'SCC-SRP', 'Serbian', 2, true, 'JAMES'),
       ('LANGUAGE', 'SCR-HRV', 'Croatian', 2, true, 'JAMES'),
       ('LANGUAGE', 'SHK', 'Shkodra', 2, true, 'JAMES'),
       ('LANGUAGE', 'SLA', 'Slavic (Other)', 2, true, 'JAMES'),
       ('LANGUAGE', 'SLO-SLK', 'Slovak', 2, true, 'JAMES'),
       ('LANGUAGE', 'SLV', 'Slovenian', 2, true, 'JAMES'),
       ('LANGUAGE', 'SPA', 'Spanish (Castilian)', 2, true, 'JAMES'),
       ('LANGUAGE', 'SWE', 'Swedish', 2, true, 'JAMES'),
       ('LANGUAGE', 'TUR', 'Turkish', 2, true, 'JAMES'),
       ('LANGUAGE', 'UKR', 'Ukrainian', 2, true, 'JAMES'),
       ('LANGUAGE', 'BUL', 'Bulgarian', 2, true, 'JAMES'),
       ('LANGUAGE', 'BOS', 'Bosnian', 2, true, 'JAMES'),
       ('LANGUAGE', 'ASP', 'Spanish (Andalusian)', 2, true, 'JAMES'),
       ('LANGUAGE', 'ALB', 'Albanian', 2, true, 'JAMES'),
       ('LANGUAGE', 'ARA', 'Arabic', 2, true, 'JAMES'),
       ('LANGUAGE', 'AFA', 'Afrossiatic', 99, true, 'JAMES'),
       ('LANGUAGE', 'AFR', 'Afrikaans', 99, true, 'JAMES'),
       ('LANGUAGE', 'AKN', 'Akan', 99, true, 'JAMES'),
       ('LANGUAGE', 'AMH', 'Amharic', 99, true, 'JAMES'),
       ('LANGUAGE', 'ARM-HYE', 'Armenian', 99, true, 'JAMES'),
       ('LANGUAGE', 'ASM', 'Assamese', 99, true, 'JAMES'),
       ('LANGUAGE', 'AUS', 'Australian or Oceanic languages', 99, true, 'JAMES'),
       ('LANGUAGE', 'AZE', 'Azerbaijani', 99, true, 'JAMES'),
       ('LANGUAGE', 'BAQ-EUS', 'Basque', 99, true, 'JAMES'),
       ('LANGUAGE', 'BAT', 'Baltic (Other)', 99, true, 'JAMES'),
       ('LANGUAGE', 'BEL', 'Belarusian', 99, true, 'JAMES'),
       ('LANGUAGE', 'BEN', 'Bengali (with Sylheti and Chatgaya)', 99, true, 'JAMES'),
       ('LANGUAGE', 'BRE', 'Breton', 99, true, 'JAMES'),
       ('LANGUAGE', 'BUR-MYA', 'Burmese', 99, true, 'JAMES'),
       ('LANGUAGE', 'CAR', 'Carib', 99, true, 'JAMES'),
       ('LANGUAGE', 'CAT', 'Catalan (Valencian)', 99, true, 'JAMES'),
       ('LANGUAGE', 'CBC', 'Caribbean Creole', 99, true, 'JAMES'),
       ('LANGUAGE', 'CEL', 'Celtic (Other)', 99, true, 'JAMES'),
       ('LANGUAGE', 'CHE', 'Chechen', 99, true, 'JAMES'),
       ('LANGUAGE', 'CHI-ZHO', 'Chinese (other)', 99, true, 'JAMES'),
       ('LANGUAGE', 'COR', 'Cornish', 99, true, 'JAMES'),
       ('LANGUAGE', 'COS', 'Corsican', 99, true, 'JAMES'),
       ('LANGUAGE', 'CSP', 'Spanish (Chilean)', 99, true, 'JAMES'),
       ('LANGUAGE', 'DAR', 'Dari', 99, true, 'JAMES'),
       ('LANGUAGE', 'ETS', 'Etsako', 99, true, 'JAMES'),
       ('LANGUAGE', 'FAO', 'Faroese', 99, true, 'JAMES'),
       ('LANGUAGE', 'FAR', 'Farsi', 99, true, 'JAMES'),
       ('LANGUAGE', 'FAS', 'Persian', 99, true, 'JAMES'),
       ('LANGUAGE', 'FIJ', 'Fijian', 99, true, 'JAMES'),
       ('LANGUAGE', 'GLA', 'Gaelic or Scottish Gaelic', 99, true, 'JAMES'),
       ('LANGUAGE', 'GLE', 'Irish', 99, true, 'JAMES'),
       ('LANGUAGE', 'GLV', 'Manx Gaelic', 99, true, 'JAMES'),
       ('LANGUAGE', 'GUJ', 'Gujarati', 99, true, 'JAMES'),
       ('LANGUAGE', 'HEB', 'Hebrew', 99, true, 'JAMES'),
       ('LANGUAGE', 'HIN', 'Hindi', 99, true, 'JAMES'),
       ('LANGUAGE', 'ICE-ISL', 'Icelandic', 99, true, 'JAMES'),
       ('LANGUAGE', 'IGB', 'Igbo', 99, true, 'JAMES'),
       ('LANGUAGE', 'ITC', 'Irish Traveller Cant', 99, true, 'JAMES'),
       ('LANGUAGE', 'JPN', 'Japanese', 99, true, 'JAMES'),
       ('LANGUAGE', 'KAL', 'Greenlandic or Kalaallisut', 99, true, 'JAMES'),
       ('LANGUAGE', 'KON', 'Konkani', 99, true, 'JAMES'),
       ('LANGUAGE', 'KOR', 'Korean', 99, true, 'JAMES'),
       ('LANGUAGE', 'KRI', 'Krio', 99, true, 'JAMES'),
       ('LANGUAGE', 'KUR', 'Kurdish', 99, true, 'JAMES'),
       ('LANGUAGE', 'LEB', 'Lebanese', 99, true, 'JAMES'),
       ('LANGUAGE', 'LIN', 'Lingala', 99, true, 'JAMES'),
       ('LANGUAGE', 'LSP', 'Spanish (Latin American)', 99, true, 'JAMES'),
       ('LANGUAGE', 'LTZ', 'Letzeburgesch or Luxembourgish', 99, true, 'JAMES'),
       ('LANGUAGE', 'LUG', 'Luganda', 99, true, 'JAMES'),
       ('LANGUAGE', 'MAN', 'Mandarin Chinese', 99, true, 'JAMES'),
       ('LANGUAGE', 'MAO-MRI', 'Maori', 99, true, 'JAMES'),
       ('LANGUAGE', 'MAR', 'Marathi', 99, true, 'JAMES'),
       ('LANGUAGE', 'MAY-MSA', 'Malay', 99, true, 'JAMES'),
       ('LANGUAGE', 'MLT', 'Maltese', 99, true, 'JAMES'),
       ('LANGUAGE', 'MNT', 'Montenegrin', 99, true, 'JAMES'),
       ('LANGUAGE', 'MOL', 'Moldavan', 99, true, 'JAMES'),
       ('LANGUAGE', 'NOB', 'Norwegian, Bokmal', 99, true, 'JAMES'),
       ('LANGUAGE', 'NPL', 'Nepalese', 99, true, 'JAMES'),
       ('LANGUAGE', 'NSL', 'North or South American Language', 99, true, 'JAMES'),
       ('LANGUAGE', 'OSL', 'Sign Languague: Any other sign language', 99, true, 'JAMES'),
       ('LANGUAGE', 'PAN', 'Panjabi', 99, true, 'JAMES'),
       ('LANGUAGE', 'PAP', 'Papiamento or Papiamentu', 99, true, 'JAMES'),
       ('LANGUAGE', 'PAS', 'Pashto', 99, true, 'JAMES'),
       ('LANGUAGE', 'PAT', 'Patois', 99, true, 'JAMES'),
       ('LANGUAGE', 'PER', 'Persian', 99, true, 'JAMES'),
       ('LANGUAGE', 'PHI', 'Filipino', 99, true, 'JAMES'),
       ('LANGUAGE', 'PPI', 'Pakistani Pahari, Mirpuri and Potwari', 99, true, 'JAMES'),
       ('LANGUAGE', 'PRA', 'Prakrit', 99, true, 'JAMES'),
       ('LANGUAGE', 'PUS', 'Pushto', 99, true, 'JAMES'),
       ('LANGUAGE', 'RIK', 'Rikiga', 99, true, 'JAMES'),
       ('LANGUAGE', 'SEN', 'Senegalese', 99, true, 'JAMES'),
       ('LANGUAGE', 'SHO', 'Shona', 99, true, 'JAMES'),
       ('LANGUAGE', 'SIN', 'Sinhala', 99, true, 'JAMES'),
       ('LANGUAGE', 'SOM', 'Somali', 99, true, 'JAMES'),
       ('LANGUAGE', 'SUDARA', 'Sudanese Arabic', 99, true, 'JAMES'),
       ('LANGUAGE', 'SWA', 'Swahili', 99, true, 'JAMES'),
       ('LANGUAGE', 'TAJ', 'Tajik', 99, true, 'JAMES'),
       ('LANGUAGE', 'TAM', 'Tamil', 99, true, 'JAMES'),
       ('LANGUAGE', 'TGL', 'Tagalog', 99, true, 'JAMES'),
       ('LANGUAGE', 'THA', 'Thai', 99, true, 'JAMES'),
       ('LANGUAGE', 'TIG', 'Tigrina', 99, true, 'JAMES'),
       ('LANGUAGE', 'TLG', 'Telugu', 99, true, 'JAMES'),
       ('LANGUAGE', 'URD', 'Urdu', 99, true, 'JAMES'),
       ('LANGUAGE', 'VIE', 'Vietnamese', 99, true, 'JAMES'),
       ('LANGUAGE', 'WOL', 'Wolof', 99, true, 'JAMES'),
       ('LANGUAGE', 'XHO', 'Xhosa', 99, true, 'JAMES'),
       ('LANGUAGE', 'YDS', 'Yiddish', 99, true, 'JAMES'),
       ('LANGUAGE', 'YOR', 'Yoruba', 99, true, 'JAMES'),
       ('LANGUAGE', 'ZHA', 'Chuang; Zhuang', 99, true, 'JAMES'),
       ('LANGUAGE', 'ZUL', 'Zulu', 99, true, 'JAMES'),
       ('LANGUAGE', 'AHA', 'Amharic', 99, false, 'JAMES');
