generic-service:
  nameOverride: hmpps-personal-relationships-api
  productId: "DPS096" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-personal-relationships-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-personal-relationships-api-cert


  # Used to access resources like SQS queues and SNS topics
  serviceAccountName: hmpps-personal-relationships-api

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_MODE: "verify-full"
    FEATURE_EVENTS_SNS_ENABLED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_PHONE_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_PHONE_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_PHONE_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_PHONE_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_PHONE_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_ADDRESS_PHONE_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_EMAIL_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_EMAIL_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_EMAIL_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_IDENTITY_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_IDENTITY_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_IDENTITY_DELETED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_RESTRICTION_CREATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_RESTRICTION_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_CONTACT_RESTRICTION_DELETED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_CREATED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_DELETED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_RESTRICTION_CREATED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_RESTRICTION_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_PRISONER_CONTACT_RESTRICTION_DELETED: true
    FEATURE_EVENT_CONTACTS_API_EMPLOYMENT_CREATED: true
    FEATURE_EVENT_CONTACTS_API_EMPLOYMENT_UPDATED: true
    FEATURE_EVENT_CONTACTS_API_EMPLOYMENT_DELETED: true
    FEATURE_EVENT_PERSONAL_RELATIONSHIPS_API_DOMESTIC_STATUS_CREATED: true
    FEATURE_EVENT_PERSONAL_RELATIONSHIPS_API_DOMESTIC_STATUS_UPDATED: true
    FEATURE_EVENT_PERSONAL_RELATIONSHIPS_API_NUMBER_OF_CHILDREN_CREATED: true
    FEATURE_EVENT_PERSONAL_RELATIONSHIPS_API_NUMBER_OF_CHILDREN_UPDATED: true
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException,org.springframework.web.servlet.resource.NoResourceFoundException,org.springframework.web.context.request.async.AsyncRequestNotUsableException"
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-personal-relationships-api-client-creds:
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    hmpps-personal-relationships-api-application-insights:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    hmpps-personal-relationships-api-sentry:
      SENTRY_AUTH_TOKEN: "SENTRY_AUTH_TOKEN"
      SENTRY_DSN: "SENTRY_DSN"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    digital-prison-reporting:
      DPR_USER: "DPR_USER"
      DPR_PASSWORD: "DPR_PASSWORD"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-personal-relationships-api