---
# Per environment values which override defaults in hmpps-personal-relationships-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: personal-relationships-api-dev.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_ORGANISATIONS: "https://organisations-api-dev.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-contacts-data-dev
  businessHoursOnly: true
